### PR TITLE
Fix #93 - caching collision for script by same name is in two locations

### LINKED ISSUE #93: caching problem if script by same name is in two locations in the file system
Just had a similar issue to #64 just come up:  

Simple case:

1. create two folders:  "test", "test2"
2. in folder "test", create a file "test.swift" with the following contents:
```
#!/usr/bin/swift sh
print("hello from 'test' folder")
```
3. copy "test.swift" into the "test2" folder.
4. edit "test2/test.swift" to change the string "hello from 'test' folder" to "hello from 'test2' folder" and save the file.
5. in terminal, cd to "test" folder and execute the test.swift file via `./test.swift`
-> builds and runs, prints:
    > hello from 'test' folder
6. still in the terminal, cd into "test2" folder and execute the test.swift file via `.test.swift`
-> ISSUE: you get the *same* string printed and test.swift is *NOT* built:
    > hello from 'test' folder
Should build test.swift and print:
    > hello from 'test2' folder

Seems like we need either a disambiguation strategy for cache folders that took into account location in the file system, or perhaps a step during swift-sh execution that validates that the Main.swift alias points to the actual file being executed and not some other copy of it somewhere in the file system.

### PR DESCRIPTION
**Pull request by haikusw**
Fix #93

bring String+md5 from xcodeproj package into main project and rename md5 to md5hash.  Use that to make cache folder name the hash of the full path to avoid collision.

### CODE REVIEW

**Comment by haikusw** [comment]
Added a test to demonstrate #93 that fails on master before adding in the fix in this PR.

**Comment by haikusw** [comment]
The failure isn't something I changed and I'm not sure what it's testing exactly:

> /Users/travis/build/mxcl/swift-sh/Tests/All/IntegrationTests.swift:31: error: -[All.RunIntegrationTests testNamingMismatch] : XCTAssertEqual failed: ("nil") is not equal to ("Optional("/")")
> 
> Test Case '-[All.RunIntegrationTests testNamingMismatch]' failed (22.886 seconds).
>

**Comment by haikusw** [comment]
All tests passed for all Linux and macOS configurations except one which seems odd.
All pass locally on 10.15.2 / Xcode 11.3:

> Test Suite 'All tests' passed at 2019-12-25 01:59:31.644.
> 	 Executed 55 tests, with 0 failures (0 unexpected) in 92.938 (92.943) seconds

**Comment by haikusw** [comment]
Same test passed on the macOS Swift 5.0.1 (10.2) and macOS 4.2.1 (Xcode 10.1) test build runs as well as both Linux builds.

I'm not seeing a way to re-run the tests short of pushing another commit or adopting travis for my entire account (which I can't do because they require access to private repos for even the free open source plan :-/ ).

**Comment by haikusw** [comment]
@mxcl so all tests passed now with just a change in white-space ¯\_(ツ)_/¯.
Any feedback on changes you need before it gets merged?  Be helpful to get this fix into version on brew so normally installed version doesn't have this problem.  TIA.

**Comment by mxcl** [comment]
Seems good, it's a pity to have a custom md5 implementation on Mac since we have common crypto, and well, shouldn’t we use a 3rd party dependency for Linux? Will merge, but perhaps consider a subsequent PR that imports the dep on Linux only.

Also whitespace is wrong, but I'll fix some time, something to watch out for in general.

**Comment by mxcl** [comment]
Actually we cannot use the imported MD5 since swift-sh is under the more liberal public domain license.

**Comment by haikusw** [comment]
Thanks for looking at this.  Pile of really good catches - thanks!

- MD5: I actually started with CryptoKit on macOS & iOS, but it's only available in 10.15/iOS13 and later. Swifth-sh works in older OS versions.  Wrote conditional stuff to make it only fix the bug in appropriate OS versions but I ran into a bug with the swift compiler: https://bugs.swift.org/browse/SR-11907 that prevented that solution.

I'll look at a CommonCrypto approach and ask MD5.swift author for permission.

Actually, wait, swift-sh already links to CryptoSwift, which contains the MD5.swift code, via the xcodeproj package, so seems like we ought to be able use it on macOS & iOS?

Still need a Linux solution.  I know nothing about Swift on linux, but I'll take a look.

- I'll fix white space. Current client project has requirements that are at odds with swift-sh settings and I fixed this multiple times must must have missed one.

Will update PR when/if I have solutions to the issues you found. Thanks for the review.

**Comment by haikusw** [comment]
Could we just use CryptoSwift as a package dependency without conflicting with xcodeproj?  CryptoSwift works on all of swift-sh's supported OSs.  I don't know SPM well enough to answer this but thinking you might.

**Comment by haikusw** [comment]
(correction: commit comment incorrectly specified the version number for Versions package; actually updated Version to from: "1.1.2" since that was the minimum required to get the "Tests" fix).

**Comment by haikusw** [comment]
Thanks!

**Comment by mxcl** [comment]
Thank you!

**Pull request merged**
