### PR TITLE
Provide tests on Linux

### PR DESCRIPTION
**Pull request by segabor**
This change enables tests on Linux

### CODE REVIEW

**Comment by segabor** [comment]
I was too eager to push this PR. Travis config needs to be enhanced with Linux test case as well.

**Comment by mxcl** [comment]
Yes. I’m doing that in the other pr

**Comment by segabor** [comment]
What about this https://github.com/segabor/swift-sh/commit/6f27964195e8eff4941e170ff6885e9197972fc5

**Comment by segabor** [comment]
Done.

**Pull request merged**
