### PR TITLE
Add relative path support for local deps

### PR DESCRIPTION
**Pull request by jasonzurita**
Issue: https://github.com/mxcl/swift-sh/issues/76

Explicitly checks for `.` and `..` prefixes, then constructs a new path from the current working directory. Finally, checks if that path exists before labeling the dependency as local.

This leverages the existing regex's allowance for these relative path prefixes.

Also, updates tests.

### CODE REVIEW

**Comment by jasonzurita** [comment]
Looks like the tests failed because they need the fix from my other PR: https://github.com/mxcl/swift-sh/pull/82

**Comment by mxcl** [comment]
Both PRs need additions to the integration tests.

**Comment by jasonzurita** [comment]
Sounds good! I will work on putting that together. Hopefully today or tomorrow.

**Comment by mxcl** [comment]
Other one is merged, if you merge master and push to this PR branch tests should pass.

**Comment by jasonzurita** [comment]
Yes, will do! I will update this a little later when I get in front of my computer :).

**Comment by jasonzurita** [comment]
fyi, this pr has been updated with the new integration test. Sorry, I forgot to mention this!

**Comment by mxcl** [comment]
This needs integration tests too IMO.

**Comment by jasonzurita** [comment]
Sounds good!

What did you have in mind? Something similar to the other test, but for one (or both) of the relative path syntax additions?

**Comment by mxcl** [comment]
It just has to verify relative path imports work.

**Pull request merged**
