### PR TITLE
Factor out import specification

### PR DESCRIPTION
**Pull request by alexito4**
Hi Max, 

I've been working on factoring out the ImportSpecification functionality of swift-sh in a separate package. My goal with this is to allow different Swift tools to share this logic so the specification on how to define the location of third party packages in a script can be standardise. 

My first step was to create a package with the needed code, you can find it in [/alexito4/ImportSpecification](https://github.com/alexito4/ImportSpecification). The package is just the code of this repo moved out, with some minor changes to namespace free functions. The test are also included and I've been keeping it up to date with your latests changes. 

The second part of the plan is to make swift-sh use this package, and so here is the PR. The functionality shouldn't have changed and all the tests are passing. Note that I've kept the extensions on `ImportSpecification` that generate the Package.swift strings here for now, as it has nothing to do with parsing the import. If other tools need it we could think of moving it out. 

Another point I went back and forth (if anybody followed the stream you could see me stress about it 😂 ) was about StreamReader. Initially I moved that into the package but that caused problems because it gets consumed after a single pass, specially when you introduced support for stdin. That's why I ended up deciding on just accepting a `String` in the library and keep the StreamReader here. If you think there is a better way of doing it (maybe you did this for performance?) we can change it no problem. 

The final part of the plan is going to other tools and adopt the package so we can have standardised imports 😄 I think I'm gonna tackle Marathon today ^^

Suffice to say that I would understand if you don't want this change on the library. I think is a good idea if we standardise this but I also can see an argument to keep it together to make it easy to evolve. In any case I had fun working on this and streaming it, and I will give a try to the final part of the plan anyway 😉 

Of course if you want to move the repo to your org that's cool too, or I can give you admin access. Whatever works best for you. 

Thanks for considering it.

### CODE REVIEW

**Comment by orta** [comment]
Looks like the fails are just linters - feels reasonable to consolidate to me. 

IMO, though, you should put energy into [making this happen in SPM]
(https://forums.swift.org/t/swift-run-scripts/18158) so these type of projects don't need to exist and there's only one way to do it.

**Comment by mxcl** [comment]
> IMO, though, you should put energy into making this happen in SPM so these type of projects don't need to exist and there's only one way to do it.

In fact, I’m working with @aciidb0mb3r on a proposal for Swift-proper

**Comment by orta** [comment]
Perfect 👍

**Comment by orta** [comment]
Haha, I thought I was replying on the marathon PR

**Comment by alexito4** [comment]
> In fact, I’m working with @aciidb0mb3r on a proposal for Swift-proper.

That's pretty cool! I can't wait to see what that exactly entails ^^

**Comment by mxcl** [comment]
K cool, you've done valuable refactoring work for me, thanks!

I do have requirements though:

1. I need to be a collaborator on your repo as I don't want development of swift-sh to be stalled because of this change
2. You have changed the behavior of `run()`, presumably by mistake, but this must be rectified.
3. A promise from you that you actually intend to actively maintain this library, and you aren't just doing this for Internet-fame.

I cannot emphasize 3 enough. My open source is a big deal to me, and while I want to merge this PR, I will not merge it if this is not a serious thing for you.

**Comment by mxcl** [comment]
Also, I made a PR that needs including in your repo: #43

**Comment by mxcl** [comment]
No, I apologize, my wording was very insensitive. I know you streamed your work, and just wanted to ensure that this project was something you actually had interest in and was not just for the sake of your stream.

**Comment by alexito4** [comment]
Merged recent changes from master 👍 
And I invited you as a collaborator to the repo.

**Comment by mxcl** [comment]
Closing for now at least, the tool is in flux and this makes me reluctant to rely on third parties for the meantime at least. Thanks for your efforts and sorry to be a grouch.

**Comment by alexito4** [comment]
Not a problem Max, thanks for taking a look.

**Pull request closed without merging**
